### ISSUE TITLE
Error loading config

### ISSUE THREAD

**Issue by jmreicha** [carlosedp/prometheus-operator-ARM#8]
Upgrading an existing Prometheus operator (from v0.17.0 to v0.28.0) and bumping the Prometheus version (v2.3.1 to v2.7.0) results in the following error in the Prometheus logs.

```
level=error ts=2019-02-01T18:43:54.10168301Z caller=main.go:688 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"
```

I haven't dug super deep into it yet, any idea what could be going on?

**Comment by carlosedp** [comment]
Prometheus Operator changed it's configuration to use jsonnet configuration template files. This happened since version 0.20.0.

I'm working right now on updating the Prometheus Stack with all latest versions. Not all dashboards have been ported yet but you can follow the progress in the https://github.com/carlosedp/prometheus-operator-ARM/tree/new-operator branch.

**Comment by jmreicha** [comment]
Cool, thanks for the quick update!

Have you been following any of the progress on official multiarch support?  https://github.com/prometheus/prometheus/pull/5031

**Comment by jmreicha** [comment]
Working now with v0.28.0.

**Comment by carlosedp** [comment]
@jmreicha I just merged the new operator structure into master.
